notifications:
  email:
    recipients:
      - rich@flatcap.org
    on_success: change
    on_failure: always

sudo: false
dist: trusty

language: c
compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - graphviz

git:
  depth: 3

env:
  global:
    - IGNORE: "Consider increasing DOT_GRAPH_MAX_NODES"

script:
  - doxygen doxygen/doxygen.conf
  - grep -v "$IGNORE" doxygen-build.txt | tee tmp.txt
  - test ! -s tmp.txt

